-- Katrinas Digital Attendance — Clean Employee Attendance V1
-- Safe migration: adds new device binding + RPC layer.
-- Does NOT change or delete existing attendance policies.

create extension if not exists pgcrypto;

create table if not exists public.employee_devices (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references public.employees(id) on delete cascade,
  branch_id bigint not null references public.branches(id) on delete restrict,
  device_token_hash text not null unique,
  active boolean not null default true,
  registered_at timestamptz not null default now(),
  last_used_at timestamptz
);

create index if not exists employee_devices_employee_idx
  on public.employee_devices(employee_id, active);

alter table public.employee_devices enable row level security;

-- No direct anon/authenticated table access is granted here.
-- The SECURITY DEFINER functions below are the controlled interface.

revoke all on public.employee_devices from anon, authenticated;

create or replace function public.employee_register_device(
  p_employee_id bigint,
  p_branch_id bigint,
  p_device_token text
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  e public.employees%rowtype;
  existing public.employee_devices%rowtype;
begin
  if p_device_token is null or length(trim(p_device_token)) < 20 then
    raise exception 'Invalid device registration.';
  end if;

  select * into e
  from public.employees
  where id = p_employee_id and active = true;

  if not found then
    raise exception 'Employee not found or inactive.';
  end if;

  if e.branch_id is not null and e.branch_id <> p_branch_id then
    raise exception 'Employee is not assigned to this branch.';
  end if;

  select * into existing
  from public.employee_devices
  where employee_id = p_employee_id
    and device_token_hash = encode(digest(p_device_token, 'sha256'), 'hex')
    and active = true
  limit 1;

  if found then
    return jsonb_build_object('ok', true, 'employee_id', e.id, 'employee_code', e.employee_code, 'full_name', e.full_name);
  end if;

  -- A phone can have one active employee binding. Registering a new employee
  -- on the same phone deactivates its previous binding.
  update public.employee_devices
  set active = false
  where device_token_hash = encode(digest(p_device_token, 'sha256'), 'hex')
    and active = true;

  insert into public.employee_devices(employee_id, branch_id, device_token_hash)
  values(e.id, p_branch_id, encode(digest(p_device_token, 'sha256'), 'hex'));

  return jsonb_build_object('ok', true, 'employee_id', e.id, 'employee_code', e.employee_code, 'full_name', e.full_name);
end;
$$;

create or replace function public.employee_time_in(
  p_employee_id bigint,
  p_branch_id bigint,
  p_device_token text,
  p_attendance_date date,
  p_time timestamptz
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  e public.employees%rowtype;
  d public.employee_devices%rowtype;
  a public.attendance%rowtype;
begin
  select * into d
  from public.employee_devices
  where employee_id = p_employee_id
    and device_token_hash = encode(digest(p_device_token, 'sha256'), 'hex')
    and active = true
  limit 1;

  if not found or d.branch_id <> p_branch_id then
    raise exception 'This phone is not registered for this employee and branch.';
  end if;

  select * into e from public.employees where id=p_employee_id and active=true;
  if not found then raise exception 'Employee not found or inactive.'; end if;

  if e.branch_id is not null and e.branch_id <> p_branch_id then
    raise exception 'Employee is not assigned to this branch.';
  end if;

  select * into a
  from public.attendance
  where employee_id=p_employee_id and attendance_date=p_attendance_date
  limit 1;

  if found and a.time_in is not null then
    raise exception 'TIME IN already recorded today.';
  end if;

  insert into public.attendance(employee_id, branch_id, attendance_date, time_in)
  values(p_employee_id,p_branch_id,p_attendance_date,p_time);

  update public.employee_devices set last_used_at=now() where id=d.id;

  return jsonb_build_object('ok',true,'type','TIME IN','attendance_date',p_attendance_date,'time',p_time);
exception
  when unique_violation then
    raise exception 'TIME IN already recorded today.';
end;
$$;

create or replace function public.employee_time_out(
  p_employee_id bigint,
  p_branch_id bigint,
  p_device_token text,
  p_attendance_date date,
  p_time timestamptz
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  d public.employee_devices%rowtype;
  a public.attendance%rowtype;
begin
  select * into d
  from public.employee_devices
  where employee_id=p_employee_id
    and device_token_hash=encode(digest(p_device_token, 'sha256'), 'hex')
    and active=true
  limit 1;

  if not found or d.branch_id <> p_branch_id then
    raise exception 'This phone is not registered for this employee and branch.';
  end if;

  select * into a
  from public.attendance
  where employee_id=p_employee_id and attendance_date=p_attendance_date
  limit 1;

  if not found or a.time_in is null then
    raise exception 'No TIME IN found for today.';
  end if;

  if a.time_out is not null then
    raise exception 'TIME OUT already recorded today.';
  end if;

  update public.attendance
  set time_out=p_time
  where id=a.id;

  update public.employee_devices set last_used_at=now() where id=d.id;

  return jsonb_build_object('ok',true,'type','TIME OUT','attendance_date',p_attendance_date,'time',p_time);
end;
$$;

revoke all on function public.employee_register_device(bigint,bigint,text) from public;
revoke all on function public.employee_time_in(bigint,bigint,text,date,timestamptz) from public;
revoke all on function public.employee_time_out(bigint,bigint,text,date,timestamptz) from public;

grant execute on function public.employee_register_device(bigint,bigint,text) to anon, authenticated;
grant execute on function public.employee_time_in(bigint,bigint,text,date,timestamptz) to anon, authenticated;
grant execute on function public.employee_time_out(bigint,bigint,text,date,timestamptz) to anon, authenticated;
